package edu.tucn.scd.serverapp.position;

import com.fasterxml.jackson.annotation.JsonProperty;
import edu.tucn.scd.serverapp.terminal.Terminal;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import java.util.Date;

/**
 * @author Radu Miron
 * @version 1
 */

@Entity // maps class to DB table, object to table row, attribute to column
@Data // lombok annotation, creates equals(), hashCode() and toString at compile time
public class Position {

    @Id // PK
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increment
    private Integer id;

    private String latitude;
    private String longitude;

    @ManyToOne(fetch = FetchType.LAZY, optional = false) // maps a many-to-one relationship; each position has a terminal; multiple positions can have the same terminal.
    @JoinColumn(name = "terminal_id", nullable = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Terminal terminal;

    @Column(updatable = false, nullable = false) // autogenerated value
    @CreationTimestamp // sets value to current time
    private Date creationDate;
}
